FROM mcr.microsoft.com/dotnet/sdk:10.0

ARG UID=1000
ARG GID=1000

ENV APP_UID=${UID}
ENV APP_GID=${GID}

RUN mkdir -p /src /home/appuser/.dotnet/tools /home/appuser/.nuget/packages && \
    chown -R ${APP_UID}:${APP_GID} /src /home/appuser

ENV DOTNET_CLI_HOME=/home/appuser
ENV NUGET_PACKAGES=/home/appuser/.nuget/packages
ENV PATH="$PATH:/home/appuser/.dotnet/tools"

USER ${APP_UID}:${APP_GID}

RUN dotnet tool install --global dotnet-ef
RUN dotnet tool install --global TeaPie.Tool

USER root

WORKDIR /src/APIKros

EXPOSE 8080

CMD mkdir -p /src/APIKros/bin /src/APIKros/obj /home/appuser/.nuget/packages && \
    chown -R ${APP_UID}:${APP_GID} /src/APIKros/bin /src/APIKros/obj /home/appuser/.nuget && \
    su $(getent passwd ${APP_UID} | cut -d: -f1) -s /bin/sh -c "dotnet restore && dotnet watch run --urls http://0.0.0.0:8080"